services:
  mysql:
    image: mysql:8.4.3
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/seeds:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  redash:
    image: redash/redash:10.1.0.b50633
    environment:
      - REDASH_DATABASE_URL=postgresql://dbuser:dbpass@pgsql:5432/redash
      - REDASH_REDIS_URL=redis://redis:6379/0
      - REDASH_SECRET_KEY=secret
      - REDASH_COOKIE_SECRET=secret
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - pgsql
      - redis
      - mysql
    ports:
      - "5000:5000"

  pgsql:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=redash
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  pgsql-data:
  redis-data:
